name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Unzip database
        run: zstd -d db.json.zst
      - name: testBaseProfile
        id: testbaseprofile
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testBaseProfile
          setup-command: ''
          command: PROFILE_MODE=base ./gradlew test --rerun-tasks --tests "hk.ust.cse.comp3021.PA2Test.test*"
          timeout: 10
          max-score: 10
      - name: testParallelProfile
        id: testparallelprofile
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testParallelProfile
          setup-command: ''
          command: PROFILE_MODE=parallel ./gradlew test --rerun-tasks --tests "hk.ust.cse.comp3021.PA2Test.test*"
          timeout: 30
          max-score: 10
      - name: testThreadPoolProfile
        id: testthreadpoolprofile
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testThreadPoolProfile
          setup-command: ''
          command: PROFILE_MODE=threadpool ./gradlew test --rerun-tasks --tests "hk.ust.cse.comp3021.PA2Test.test*"
          timeout: 30
          max-score: 10
      - name: testParallelProfileTime
        id: testparallelprofiletime
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testParallelProfileTime
          setup-command: ''
          command: ./gradlew test --tests "hk.ust.cse.comp3021.PA3Test.testParallelProfileTime"
          timeout: 30
          max-score: 15
      - name: testThreadPoolProfileTime
        id: testthreadpoolprofiletime
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: testThreadPoolProfileTime
          setup-command: ''
          command: ./gradlew test --tests "hk.ust.cse.comp3021.PA3Test.testThreadPoolProfileTime"
          timeout: 10
          max-score: 15
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TESTBASEPROFILE_RESULTS: "${{steps.testbaseprofile.outputs.result}}"
          TESTPARALLELPROFILE_RESULTS: "${{steps.testparallelprofile.outputs.result}}"
          TESTTHREADPOOLPROFILE_RESULTS: "${{steps.testthreadpoolprofile.outputs.result}}"
          TESTPARALLELPROFILETIME_RESULTS: "${{steps.testparallelprofiletime.outputs.result}}"
          TESTTHREADPOOLPROFILETIME_RESULTS: "${{steps.testthreadpoolprofiletime.outputs.result}}"
        with:
          runners: testbaseprofile,testparallelprofile,testthreadpoolprofile,testparallelprofiletime,testthreadpoolprofiletime